# Generated by Django 6.0.5 on 2026-05-29 05:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_job_job_type_alter_job_experience_alter_job_skills'), ('core', '0003_userprofile'), ('core', '0004_userprofile_created_at_alter_job_job_type_and_more'), ('core', '0005_remove_job_job_type_job_conditions_job_logo_and_more'), ('core', '0006_job_category'), ('core', '0007_job_company_type'), ('core', '0008_job_s_sponsored'), ('core', '0009_rename_s_sponsored_job_is_sponsored'), ('core', '0010_job_is_featured'), ('core', '0011_job_created_at'), ('core', '0012_remove_job_posted'), ('core', '0013_alter_job_work_mode'), ('core', '0014_alter_job_category_alter_job_logo'), ('core', '0015_alter_job_company_type'), ('core', '0016_companyrating'), ('core', '0017_alter_companyrating_unique_together'), ('core', '0018_delete_companyrating'), ('core', '0019_job_role_category'), ('core', '0020_job_duration'), ('core', '0021_job_education'), ('core', '0022_alter_job_education'), ('core', '0023_job_posted_by'), ('core', '0024_alter_job_posted_by'), ('core', '0025_job_industry'), ('core', '0026_job_posted_date'), ('core', '0027_remove_job_posted_date'), ('core', '0028_remove_job_salary_job_max_salary_job_min_salary'), ('core', '0029_savedjob'), ('core', '0030_job_rating_job_review_count'), ('core', '0031_applyjob'), ('core', '0032_alter_applyjob_status'), ('core', '0033_userprofile_company_name_userprofile_role_and_more'), ('core', '0034_userprofile_email_verified_emailverification'), ('core', '0035_job_employer_job_views_application'), ('core', '0036_remove_job_views'), ('core', '0037_job_views'), ('core', '0038_jobapplication'), ('core', '0039_interview'), ('core', '0040_message'), ('core', '0041_companyprofile'), ('core', '0042_alter_companyprofile_founded_year'), ('core', '0043_subscription'), ('core', '0044_employersettings'), ('core', '0045_application_resume'), ('core', '0046_alter_application_status'), ('core', '0047_job_description'), ('core', '0048_remove_application_applied_at'), ('core', '0049_application_applied_at'), ('core', '0050_application_experience'), ('core', '0051_application_location'), ('core', '0052_application_skills'), ('core', '0053_application_interview_date_and_more'), ('core', '0054_alter_application_status'), ('core', '0055_alter_application_status'), ('core', '0056_job_is_active'), ('core', '0057_job_status'), ('core', '0058_job_job_type'), ('core', '0059_application_phone_number_job_company_name'), ('core', '0060_alter_application_status_delete_jobapplication'), ('core', '0061_application_degree'), ('core', '0062_delete_applyjob'), ('core', '0063_remove_application_degree_applyjob'), ('core', '0064_userprofile_location_userprofile_skills'), ('core', '0065_companyprofile_benefits_companyprofile_city_and_more'), ('core', '0066_delete_subscription'), ('core', '0067_alter_job_category'), ('core', '0068_alter_job_category'), ('core', '0069_job_department_job_nature_of_business'), ('core', '0070_interviewquestion'), ('core', '0071_delete_interviewquestion'), ('core', '0072_job_salary_disclosed_alter_job_max_salary_and_more'), ('core', '0073_remove_job_department_remove_job_job_type_and_more'), ('core', '0074_job_department_job_job_type_job_nature_of_business_and_more')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('work_status', models.CharField(blank=True, choices=[('experienced', 'Experienced'), ('fresher', 'Fresher')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('role', models.CharField(choices=[('candidate', 'Candidate'), ('employer', 'Employer')], default='candidate', max_length=20)),
                ('email_verified', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=300)),
                ('experience', models.CharField(max_length=50)),
                ('conditions', models.CharField(default='Hands-on projects • Paper writing • Coding explanation', max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('work_mode', models.CharField(choices=[('Remote', 'Remote'), ('On-site', 'On-site'), ('Hybrid', 'Hybrid')], max_length=50)),
                ('category', models.CharField(choices=[('IT', 'IT'), ('Sales', 'Sales'), ('HR', 'HR'), ('General', 'General'), ('Finance & Accounting', 'Finance & Accounting'), ('Marketing', 'Marketing')], default='General', max_length=100)),
                ('company_type', models.CharField(choices=[('MNC', 'MNC'), ('Startup', 'Startup'), ('Product', 'Product'), ('Unicorn', 'Unicorn')], default='MNC', max_length=50)),
                ('is_sponsored', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('role_category', models.CharField(default='temp', max_length=100)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('education', models.CharField(choices=[('PG', 'Any Postgraduate'), ('MBA', 'MBA/PGDM'), ('GRAD', 'Any Graduate'), ('BTECH', 'B.Tech/B.E.'), ('DIP', 'Diploma'), ('12TH', '12th Pass')], max_length=50)),
                ('posted_by', models.CharField(choices=[('COMPANY', 'Company Jobs'), ('CONSULTANT', 'Consultant Jobs')], default='COMPANY', max_length=20)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('max_salary', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('min_salary', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('rating', models.DecimalField(decimal_places=1, default=3.5, max_digits=2)),
                ('review_count', models.IntegerField(default=0)),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('views', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('salary_disclosed', models.BooleanField(default=True)),
                ('department', models.CharField(blank=True, choices=[('Sales & Business Development', 'Sales & Business Development'), ('Engineering - Software & QA', 'Engineering - Software & QA'), ('Marketing & Communication', 'Marketing & Communication'), ('Human Resources', 'Human Resources'), ('Finance & Accounting', 'Finance & Accounting'), ('Operations', 'Operations')], max_length=100, null=True)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship')], default='Full Time', max_length=20)),
                ('nature_of_business', models.CharField(blank=True, choices=[('B2B', 'B2B'), ('B2C', 'B2C'), ('SaaS', 'SaaS'), ('D2C', 'D2C'), ('PaaS', 'PaaS')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('draft', 'Draft')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(max_length=100)),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('meeting_link', models.URLField()),
                ('status', models.CharField(default='Scheduled', max_length=50)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('dark_mode', models.BooleanField(default=False)),
                ('language', models.CharField(default='English', max_length=50)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Screening', 'Screening'), ('Shortlisted', 'Shortlisted'), ('Interview', 'Interview'), ('Interview Scheduled', 'Interview Scheduled'), ('Technical', 'Technical'), ('HR', 'HR'), ('Offer', 'Offer'), ('Rejected', 'Rejected')], default='Applied', max_length=50)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.job')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('applied_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('experience', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('skills', models.CharField(blank=True, max_length=300, null=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_link', models.URLField(blank=True, null=True)),
                ('interview_notes', models.TextField(blank=True, null=True)),
                ('interview_time', models.TimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Selected', 'Selected')], default='Applied', max_length=30)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('employee_count', models.CharField(blank=True, max_length=50)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('benefits', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('company_type', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('hr_contact', models.CharField(blank=True, max_length=100)),
                ('hr_email', models.EmailField(blank=True, max_length=254)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('other_link', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('technologies', models.CharField(blank=True, max_length=500)),
                ('twitter', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
