# Generated by Django 5.2.9 on 2026-04-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_created_at_alter_job_job_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.AddField(
            model_name='job',
            name='conditions',
            field=models.CharField(default='Hands-on projects • Paper writing • Coding explanation', max_length=300),
        ),
        migrations.AddField(
            model_name='job',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='job',
            name='posted',
            field=models.CharField(default='Few hours ago', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='work_mode',
            field=models.CharField(default='Remote', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.CharField(max_length=300),
        ),
    ]
