# Generated by Django 5.2.9 on 2026-04-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_job_job_type_job_conditions_job_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
