# Generated by Django 5.2.9 on 2026-04-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
