# Generated by Django 5.2.9 on 2026-04-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_job_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='s_sponsored',
            field=models.BooleanField(default=False),
        ),
    ]
