# Generated by Django 5.2.9 on 2026-04-11 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_job_s_sponsored'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='s_sponsored',
            new_name='is_sponsored',
        ),
    ]
