# Generated by Django 5.2.9 on 2026-04-20 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_job_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='posted',
        ),
    ]
