# Generated by Django 5.2.9 on 2026-04-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_job_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='work_mode',
            field=models.CharField(choices=[('Remote', 'Remote'), ('On-site', 'On-site'), ('Hybrid', 'Hybrid')], max_length=50),
        ),
    ]
