# Generated by Django 5.2.9 on 2026-04-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_job_work_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('IT', 'IT'), ('Sales', 'Sales'), ('HR', 'HR'), ('General', 'General')], default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
