# Generated by Django 5.2.9 on 2026-04-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_job_category_alter_job_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_type',
            field=models.CharField(choices=[('MNC', 'MNC'), ('Startup', 'Startup'), ('Product', 'Product'), ('Unicorn', 'Unicorn')], default='MNC', max_length=50),
        ),
    ]
