# Generated by Django 5.2.9 on 2026-04-21 05:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_companyrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyrating',
            unique_together={('job', 'user')},
        ),
    ]
