# Generated by Django 5.2.9 on 2026-04-21 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_companyrating_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyRating',
        ),
    ]
