# Generated by Django 5.2.9 on 2026-04-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_delete_companyrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='role_category',
            field=models.CharField(default='temp', max_length=100),
            preserve_default=False,
        ),
    ]
