# Generated by Django 5.2.9 on 2026-04-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_job_role_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
