# Generated by Django 5.2.9 on 2026-04-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_job_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='education',
            field=models.CharField(choices=[('PG', 'Any Postgraduate'), ('MBA', 'MBA/PGDM'), ('GRAD', 'Any Graduate'), ('BTECH', 'B.Tech/B.E.'), ('DIP', 'Diploma'), ('12TH', '12th Pass')], default='any', max_length=20),
            preserve_default=False,
        ),
    ]
