# Generated by Django 5.2.9 on 2026-04-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_job_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='education',
            field=models.CharField(choices=[('PG', 'Any Postgraduate'), ('MBA', 'MBA/PGDM'), ('GRAD', 'Any Graduate'), ('BTECH', 'B.Tech/B.E.'), ('DIP', 'Diploma'), ('12TH', '12th Pass')], max_length=50),
        ),
    ]
