# Generated by Django 5.2.9 on 2026-04-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_job_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='posted_by',
            field=models.CharField(choices=[('COMPANY', 'Company Jobs'), ('CONSULTANT', 'Consultant Jobs')], default='COMPANY', max_length=20),
        ),
    ]
