# Generated by Django 5.2.9 on 2026-04-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_job_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
