# Generated by Django 5.2.9 on 2026-04-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_job_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
