# Generated by Django 5.2.9 on 2026-04-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_job_posted_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='posted_date',
        ),
    ]
