# Generated by Django 5.2.9 on 2026-05-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=3.5, max_digits=2),
        ),
        migrations.AddField(
            model_name='job',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
