# Generated by Django 5.2.9 on 2026-05-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_applyjob_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('employer', 'Employer')], default='candidate', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work_status',
            field=models.CharField(blank=True, choices=[('experienced', 'Experienced'), ('fresher', 'Fresher')], max_length=20, null=True),
        ),
    ]
