# Generated by Django 6.0.5 on 2026-05-08 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_job_employer_job_views_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='views',
        ),
    ]
