# Generated by Django 6.0.5 on 2026-05-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_companyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
