# Generated by Django 6.0.5 on 2026-05-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_application_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Screening', 'Screening'), ('Shortlisted', 'Shortlisted'), ('Interview', 'Interview'), ('Technical', 'Technical'), ('HR', 'HR'), ('Offer', 'Offer'), ('Rejected', 'Rejected')], default='Applied', max_length=50),
        ),
    ]
