# Generated by Django 6.0.5 on 2026-05-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applied_at',
        ),
    ]
