# Generated by Django 6.0.5 on 2026-05-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_application_applied_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
