# Generated by Django 6.0.5 on 2026-05-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_application_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='skills',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
