# Generated by Django 6.0.5 on 2026-05-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_application_interview_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Screening', 'Screening'), ('Shortlisted', 'Shortlisted'), ('Interview', 'Interview'), ('Technical', 'Technical'), ('HR', 'HR'), ('Offer', 'Offer'), ('Rejected', 'Rejected'), ('Interview Scheduled', 'Interview Scheduled')], default='Applied', max_length=50),
        ),
    ]
