# Generated by Django 6.0.5 on 2026-05-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_application_phone_number_job_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Screening', 'Screening'), ('Shortlisted', 'Shortlisted'), ('Interview', 'Interview'), ('Interview Scheduled', 'Interview Scheduled'), ('Technical', 'Technical'), ('HR', 'HR'), ('Offer', 'Offer'), ('Rejected', 'Rejected')], default='Applied', max_length=50),
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
