# Generated by Django 6.0.5 on 2026-05-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_application_status_delete_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
