# Generated by Django 6.0.5 on 2026-05-15 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_application_degree'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplyJob',
        ),
    ]
