# Generated by Django 6.0.5 on 2026-05-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_companyprofile_benefits_companyprofile_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
