# Generated by Django 6.0.5 on 2026-05-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_delete_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('IT', 'IT'), ('Sales', 'Sales'), ('HR', 'HR'), ('General', 'General'), ('Finance & Accounting', 'Finance & Accounting'), ('Marketing', 'Marketing'), ('Software Development', 'Software Development'), ('Engineering', 'Engineering'), ('Data Science', 'Data Science'), ('Human Resources', 'Human Resources'), ('Banking & Finance', 'Banking & Finance'), ('Project Management', 'Project Management')], default='General', max_length=100),
        ),
    ]
