# Generated by Django 6.0.5 on 2026-05-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('IT', 'IT'), ('Sales', 'Sales'), ('HR', 'HR'), ('General', 'General'), ('Finance & Accounting', 'Finance & Accounting'), ('Marketing', 'Marketing')], default='General', max_length=100),
        ),
    ]
