# Generated by Django 6.0.5 on 2026-05-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(blank=True, choices=[('Sales & Business Development', 'Sales & Business Development'), ('Engineering - Software & QA', 'Engineering - Software & QA'), ('Marketing & Communication', 'Marketing & Communication'), ('Human Resources', 'Human Resources'), ('Finance & Accounting', 'Finance & Accounting'), ('Operations', 'Operations')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='nature_of_business',
            field=models.CharField(blank=True, choices=[('B2B', 'B2B'), ('B2C', 'B2C'), ('SaaS', 'SaaS'), ('D2C', 'D2C'), ('PaaS', 'PaaS')], max_length=10, null=True),
        ),
    ]
