# Generated by Django 6.0.5 on 2026-05-20 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_interviewquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterviewQuestion',
        ),
    ]
