# Generated by Django 6.0.5 on 2026-05-23 04:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_delete_interviewquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary_disclosed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='max_salary',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='job',
            name='min_salary',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
