# Generated by Django 6.0.5 on 2026-05-23 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_job_salary_disclosed_alter_job_max_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='department',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='nature_of_business',
        ),
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
    ]
