# Generated by Django 6.0.5 on 2026-05-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_remove_job_department_remove_job_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(blank=True, choices=[('Sales & Business Development', 'Sales & Business Development'), ('Engineering - Software & QA', 'Engineering - Software & QA'), ('Marketing & Communication', 'Marketing & Communication'), ('Human Resources', 'Human Resources'), ('Finance & Accounting', 'Finance & Accounting'), ('Operations', 'Operations')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship')], default='Full Time', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='nature_of_business',
            field=models.CharField(blank=True, choices=[('B2B', 'B2B'), ('B2C', 'B2C'), ('SaaS', 'SaaS'), ('D2C', 'D2C'), ('PaaS', 'PaaS')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('draft', 'Draft')], default='active', max_length=20),
        ),
    ]
