# Generated by Django 6.0.5 on 2026-05-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_alter_application_applied_at_alter_job_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_name',
        ),
    ]
