# Generated by Django 6.0.5 on 2026-06-09 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_remove_job_experience_job_max_experience_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['location', 'job_type'], name='core_job_locatio_12942e_idx'),
        ),
    ]
