# Generated by Django 6.0.5 on 2026-06-11 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_alter_userprofile_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplyJob',
        ),
    ]
