# Generated by Django 6.0.5 on 2026-06-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_delete_applyjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
