# Generated by Django 6.0.5 on 2026-06-11 11:01

import re
import json
from django.db import migrations, models


def clean_experience(apps, schema_editor):
    Application = apps.get_model('core', 'Application')
    for app in Application.objects.all():
        val = app.experience
        if val is None:
            continue
        match = re.search(r'\d+', str(val))
        app.experience = int(match.group()) if match else 0
        app.save()


def clean_skills(apps, schema_editor):
    Application = apps.get_model('core', 'Application')
    for app in Application.objects.all():
        val = app.skills
        if not val:
            app.skills = '[]'
            app.save()
            continue
        # already valid JSON like ["Python", "Django"] — skip
        try:
            json.loads(val)
        except (json.JSONDecodeError, TypeError):
            # plain text like "Python, Django, JavaScript" → convert to JSON list
            skills_list = [s.strip() for s in str(val).split(',') if s.strip()]
            app.skills = json.dumps(skills_list)
            app.save()


def reverse_clean(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_alter_userprofile_skills'),
    ]

    operations = [
        migrations.RunPython(clean_experience, reverse_clean),
        migrations.AlterField(
            model_name='application',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(clean_skills, reverse_clean),
        migrations.AlterField(
            model_name='application',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]